services:
  db:
    image: postgres:17.4
    restart: always
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=name
    ports:
      - '5050:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
